Tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import halaman_login_status.urls as halaman_login_status
import halaman_profile.urls as halaman_profile
import halaman_riwayat.urls as halaman_riwayat
import halaman_cari_mahasiswa.urls as halaman_cari_mahasiswa
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'fitur1/', include(halaman_login_status, namespace = 'fitur1')),
    url(r'fitur2/', include(halaman_profile, namespace = 'fitur2')),
    url(r'riwayat/', include(halaman_riwayat, namespace = 'riwayat')),
    url(r'cari-mahasiswa/', include(halaman_cari_mahasiswa, namespace = 'cari-mahasiswa')),
    url(r'^$', RedirectView.as_view(url='/fitur1/', permanent = True)),
]

halaman_login_status/urls.py
from django.conf.urls import url
from .views import index, add_status, dummy, halaman_status
from .custom_auth import auth_login, auth_logout


urlpatterns = [
	url(r'^$', dummy, name='dummy'),
	url(r'^login', index, name='index'),
	url(r'^halaman_status', halaman_status, name='halaman_status'),
	url(r'^add_status', add_status, name='add_status'),

	# custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

halaman_login_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField(default="Empty")
    created_date = models.DateTimeField(auto_now_add=True)

halaman_login_status/forms.py
from django import forms

class Status_Form(forms.Form):
	error_message = {
		'required': 'Have nothing to post?',
	}
	status_attrs = {
		'type': 'text',
		'cols': 147,
		'rows': 4,
		'class': 'status-form-textarea',
		'placeholder': "Write your day here!"
	}

	status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

halaman_login_status/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.utils import timezone

from .forms import Status_Form
from .models import Status
# Create your views here.

response = {}

def dummy(request):
	if 'user_login' in request.session:
		return HttpResponseRedirect(reverse('fitur1:halaman_status'))
	html = 'halaman_login_status/session/dummy.html'
	return render(request, html, response)

def index(request):
	print("#==> masuk index")
	if 'user_login' in request.session:
		return HttpResponseRedirect(reverse('fitur1:halaman_status'))
	else:
		html = 'halaman_login_status/session/login.html'
		return render(request, html, response)

def halaman_status(request):
	print ("#==> halaman_status")

	if 'user_login' not in request.session.keys():
		return HttpResponseRedirect(reverse('fitur1:index'))

	set_data_for_session(response, request)
		
	html = 'halaman_login_status/layout/base.html'
	return render(request, html, response)		

def set_data_for_session(res, request):
	response['author'] = request.session['user_login']
	response['access_token'] = request.session['access_token']
	response['kode_identitas'] = request.session['kode_identitas']
	response['status'] = Status.objects.all()
	response['jumlah_status'] = Status.objects.all().count()
	response['status_form'] = Status_Form
	response['latest_post'] = Status.objects.last()

def add_status(request):
	form = Status_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'])
		status.save()
		return HttpResponseRedirect('/fitur1/halaman_status')
	else:
		return HttpResponseRedirect('/fitur1/halaman_status')	

halaman_login_status/templates/halaman_login_status/halaman_status.html
{% load staticfiles %}
<section name="input-status" id="input-status">
    <div class="container">
        <form id="form", method="POST", action="{% url 'fitur1:add_status' %}">
            {% csrf_token %}
            {{ status_form }}
            <p></p>
            <input id="post", type="submit", class="btn btn-default", value="Post", style="float:right">
            <br>
        </form>
    </div>
</section>
<section name="all-status" id="all-status">
    <div class="container">
        <div class="flex">
            {% if status %}             
                {% for data in status reversed %}
                    <div>
                        <div class="show-status">
                            <div class="status-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="status-content">
                                <pre>{{data.status}}</pre>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>No status added.</strong> Add your status now!
            </div>
            {% endif %}
        </div>
    </div>
</section>