Tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import halaman_login_status.urls as halaman_login_status
import halaman_profile.urls as halaman_profile
import halaman_riwayat.urls as halaman_riwayat
import halaman_cari_mahasiswa.urls as halaman_cari_mahasiswa
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'fitur1/', include(halaman_login_status, namespace = 'fitur1')),
    url(r'fitur2/', include(halaman_profile, namespace = 'fitur2')),
    url(r'riwayat/', include(halaman_riwayat, namespace = 'riwayat')),
    url(r'cari-mahasiswa/', include(halaman_cari_mahasiswa, namespace = 'cari-mahasiswa')),
    url(r'^$', RedirectView.as_view(url='/fitur1/', permanent = True)),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, save_database
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit/$', edit_profile, name='edit_profile'),
    url(r'^save_database/$', save_database, name='save_database'),
]

halaman_profile/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.

class User(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, default='Kosong')
    name = models.CharField('Nama', max_length=225)
    email = models.EmailField('Email', default='Kosong')
    profileUrl = models.URLField('Profile LinkedIn', default='Kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Expertise(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=27)
    expert = models.CharField('Keahlian', max_length=27, default='Kosong')
    kejagoan = models.CharField('Kejagoan', max_length=27, default='Kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

halaman_profile/views.py
from __future__ import unicode_literals
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import User, Expertise


response = {}

def index(request):
    if 'user_login' in request.session:
        response['name'] = 'Tugas 2 PPW'
        html = 'halaman_profile/halaman_profile.html'
        response['login'] = True
        response['kode_identitas'] = request.session['kode_identitas']
        exist = User.objects.filter(kode_identitas=1).exists()
        response['jumlahKosong'] = set_data_user(request, exist)
        response['nama_identitas'] = request.session['user_login']


        return render(request, html, response)

    else:
        response['connected'] = False #digunakan sebagai penanda kapan header menampilkan tombol logout
        response['name'] = 'Tugas 2 PPW'
        response['login'] = False
        html = 'halaman_login_status/halaman_status.html'
        return HttpResponseRedirect(request, html, response)

def edit_profile(request):
    if 'user_login' in request.session:
        response['name'] = 'Tugas 2 PPW'
        html = 'halaman_profile/edit_profile.html'
        return render(request, html, response)
    else:
        response['connected'] = False #digunakan sebagai penanda kapan header menampilkan tombol logout
        response['name'] = 'Tugas 2 PPW'
        response['login'] = False
        html = 'halaman_login_status/halaman_status.html'
        return render(request, html, response)

@csrf_exempt
def save_database(request):
    if(request.method == 'POST'):
        name = request.POST['firstName'] + ' ' + request.POST['lastName']
        email = request.POST['email']
        profileUrl = request.POST['profileUrl']
        kode_identitas = 1
        user = User(name=name, email=email, profileUrl=profileUrl, kode_identitas=kode_identitas)
        user.save()

def set_data_user(request, exist):
	counterKosong = 0
	if exist:
		user = User.objects.get(kode_identitas=1)
		response['userName'] = user.name
		response['userEmail'] = user.email
		response['userProfileLinkedIn'] = user.profileUrl
	else:
		counterKosong = 3
		response['userName'] = 'kosong'
		response['userEmail'] = 'kosong'
		response['userProfileLinkedIn'] = 'kosong'
	expertiseExist = Expertise.objects.filter(kode_identitas=1).exists()
	if not expertiseExist:
		counterKosong += 1
		response['userKeahlian'] = 'kosong'
	return counterKosong

halaman_profile/templates/halaman_profile/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 9">
    <meta name="author" content="Tugas 2 PPW">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }
    </style>
    <title>
        {% block title %} Tugas 2 By Tugas 2 PPW {% endblock %}
    </title>
</head>
<body>
<header>
    {% include "halaman_profile/partials/header.html" %}
</header>
<content>
    <div class="w3-bar w3-black">
        <a class="w3-bar-item w3-button" id="Profile" href="{% url 'fitur2:index' %}">Profile</a>
        <a class="w3-bar-item w3-button" id="Riwayat" href="{% url 'riwayat:index' %}">Riwayat</a>
        <a class="w3-bar-item w3-button" id="Status" href="{% url 'fitur1:index' %}">Status</a>
        <a class="w3-bar-item w3-button" id="Teman" href="{% url 'cari-mahasiswa:index' %}">Teman</a>

    </div>
    {% block content %}
    <!-- Your Content Here -->
    {% endblock %}
</content>
<footer>
    <hr>
    {% block footer %}
    {% include "halaman_profile/partials/footer.html" %}
    {% endblock %}
</footer>
<script>
    function openApp(appName){
        if(appName == 'profile'){
            window.location.href = "/fitur2/";
        }
        else if(appName == 'riwayat'){
            window.location.href = "/mahasiswa/riwayat/";
        }
        else if(appName == 'search'){
            window.location.href = "/mahasiswa/search/";
        }
    };
</script>
<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>